### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by georgbachmann** [codetheweb/homebridge-yamaha-scene#1]
Hello,
I haven't really figured out how to properly use your plugin.
What I'd like to do is to create let's say two scenes. One is for "Movie Time" where the receiver should change the input to my Apple-TV and set volume to let's say -32. Then I'd like to have one let's say "Breakfast" where I'd like it to change to radio and set the volume to -35 or so...
I tried to simply create two entries in the accessories part of my homebride config, and now I have two switches showing up in HomeKit. But switching between them doesn't work... If I tap one, the AV-Receiver powers on. If I tap the other one it changes correctly. Then when tapping the other one again, the receiver powers off...
Am I  doing something wrong?
Oh... and what is the `"scene": 1,` in your sample? And how can I set the input? In my sample above I just tried changing the volume for demo/testing purposes...

Cheers,
Georg

**Comment by codetheweb** [comment]
The `scene` parameter is intended to be used to switch between scenes, which can be programed by changing the desired settings on your receiver (not including volume), and then holding down one of the 4 circular buttons (TV, NET, etc).  The `scene` parameter corresponds to one of those buttons.
As for it powering off, that's its intended functionality.  Here's what happens:
1. You tap (a) on.  The receiver powers on, switches scenes, and sets the volume.
2. You tap (b) on.  The receiver stays on, switches scenes, and sets the volume.
3. You tap (a) once again.  Since the receiver is already on, tapping it again turns it off.

If you want to create an acessory that just switches between scenes, you'll have to fork this or create a pull request, adding a parameter that keeps the receiver from powering off.

Sorry about the lack of documentation, I didn't figure anyone else would ever use this 😛.
