### ISSUE TITLE
Scene activation does not work on RX-V475

### ISSUE THREAD

**Issue by sivoba** [codetheweb/homebridge-yamaha-scene#2]
Switching on/off works fine, automated adjusting of the volume to the preset level works also. Unfortunately the chosen scene is not activated. Any ideas?

**Comment by codetheweb** [comment]
Duplicate of #1. Honestly, because of the way I'm currently using this I'm not planning on changing it anytime soon.

However, you're more than welcome to fix it and open a pull request :). It shouldn't be too hard, just add an option for `config.json` on whether or not to consider a currently disabled scene as powered off.
